draw_bar();
slider.bar._visible = true;
man.gotoandstop(1);
keeps.gotoandplay(1);
keeps._x = 263;
status = 0;
bounce = 0;
bounced = 1;
bounceyball = 0;
cchecked = false;
end = 0;
dy = 0;
lev = sidney;
ybit = 8;
lpost = 135;
rpost = 430;
barpos = 50;
barh = 105;
posttolerance = 13;
bwidth = 10;
rightcorner = 0;
leftcorner = 0;
corner = 0;
topnet = 0;
hitbar = false;
rposthit = false;
lposthit = false;
checked = false;
innet = false;
dive = false;
_level0.kicked = false;
_level0.checked = false;
